export const GET_LAYOUT_DATA = 'GET_LAYOUT_DATA'

export const SET_USERINFO_DATA = 'SET_USERINFO_DATA'

export const SET_ROUTERS_DATA = 'SET_ROUTERS_DATA'

export const SET_ROUTER_DATA = 'SET_ROUTER_DATA'

export const SET_JURISD_DATA = 'SET_JURISD_DATA'

export const SET_JURISDICTION_DATA = 'SET_JURISDICTION_DATA'

export const SET_JURISDICTION_OPTIONS_DATA = 'SET_JURISDICTION_OPTIONS_DATA'

export const GET_JURISDICTION = 'GET_JURISDICTION'

export const SET_COLLAPSED = 'SET_COLLAPSED'

export const SET_LOGIN = 'SET_LOGIN'

export const SET_SOLO = 'SET_SOLO'

export const GET_ROUTER = 'GET_ROUTER'

export const GET_ICONS = 'GET_ICONS'

export const SET_ICONS_DATA = 'SET_ICONS_DATA'

export const SET_USERLIST_DATA = 'SET_USERLIST_DATA'

export const GET_USERLIST = 'GET_USERLIST'

export const SET_ARTICLE_DATA = 'SET_ARTICLE_DATA'

export const GET_ARTICLE = 'GET_ARTICLE'

export const SET_IMAGES_DATA = 'SET_IMAGES_DATA'

export const SET_IMAGE_MODAL_VISIBLE = 'SET_IMAGE_MODAL_VISIBLE'

export const SET_COMPONENT_DATA = 'SET_COMPONENT_DATA'